overrides:
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  bn.js@<4.12.3: '>=4.12.3'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=5.0.0 <5.3.5: '>=5.3.5'
  fast-xml-parser@>=5.0.0 <5.3.6: '>=5.3.6'
  fast-xml-parser@>=5.0.0 <5.3.8: '>=5.3.8'
  jspdf@<4.2.0: '>=4.2.0'
